### ISSUE TITLE
Mail queues not working

### ISSUE THREAD

**Issue by pinodex** [barryvdh/laravel-async-queue#66]
Queues are not working whenever I try to send emails with it. (e.g. with mail notification or a call to `Mail::to`). When I run the command `php artisan queue:async <id>`, it gives me this exception

    [Symfony\Component\Debug\Exception\FatalThrowableError]
    Call to a member function getName() on null

### Steps to reproduce:

1. Create a notification with `php artisan make:notification TestNotification`.
2. By default, the `toMail` method should contain the following code

```
public function toMail($notifiable)
{
    return (new MailMessage)
        ->line('The introduction to the notification.')
        ->action('Notification Action', url('/'))
        ->line('Thank you for using our application!');
}
```   
3. Notify the user with the TestNotification. The user model should contain a valid email address in its `email` attribute.
```
User::find(1)->notify(new TestNotification);
```
4. Observe that you will not receive your email notification.
5. Get the job ID in the `jobs` table, and try with `php artisan queue:async <id>`.
6. You will get the exception above.

#### This also occurs with `Mail::to`.

1. Create a new job. `php artisan make:job TestJob`
2. Create a new mailable and configure your email view. `php artisan make:mail TestEmail`
3. In the `handle` method, add the following code
```
public function handle()
{
     Mail::to('<email address>')->send(new TestEmail);
}
```
4. Dispatch the job
```
dispatch(new TestJob);
```
5. Observe that you will not receive your email notification.
6. Get the job ID in the `jobs` table, and try with `php artisan queue:async <id>`.
7. You will get the exception above.

**Comment by barryvdh** [comment]
Can you post the stacktrace? Should be in your logs.

**Comment by pinodex** [comment]
Here's the stack trace

```
[2017-04-28 15:42:32] dev.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getName() on null in <root>\app\Providers\ViewServiceProvider.php:36
Stack trace:
#0 <root>\vendor\laravel\framework\src\Illuminate\View\Concerns\ManagesEvents.php(164): App\Providers\ViewServiceProvider->App\Providers\{closure}(Object(Illuminate\View\View))
#1 <root>\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(332): Illuminate\View\Factory->Illuminate\View\Concerns\{closure}('composing: noti...', Array)
#2 <root>\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('composing: noti...', Array)
#3 <root>\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(172): Illuminate\Events\Dispatcher->dispatch('composing: noti...', Array, false)
#4 <root>\vendor\laravel\framework\src\Illuminate\View\Concerns\ManagesEvents.php(179): Illuminate\Events\Dispatcher->fire('composing: noti...', Array)
#5 <root>\vendor\laravel\framework\src\Illuminate\View\View.php(118): Illuminate\View\Factory->callComposer(Object(Illuminate\View\View))
#6 <root>\vendor\laravel\framework\src\Illuminate\View\View.php(85): Illuminate\View\View->renderContents()
#7 <root>\vendor\laravel\framework\src\Illuminate\Mail\Markdown.php(62): Illuminate\View\View->render()
#8 <root>\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(78): Illuminate\Mail\Markdown->render('notifications::...', Array)
#9 <root>\vendor\laravel\framework\src\Illuminate\Notifications\Channels\MailChannel.php(58): Illuminate\Notifications\Channels\MailChannel->buildView(Object(Illuminate\Notifications\Messages\MailMessage))
#10 <root>\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\User), Object(App\Notifications\TestNotification))
#11 <root>\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\User), '28071aa5-9296-4...', Object(App\Notifications\TestNotification), 'mail')
#12 <root>\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(51): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\TestNotification), Array)
#13 <root>\vendor\laravel\framework\src\Illuminate\Notifications\SendQueuedNotifications.php(57): Illuminate\Notifications\ChannelManager->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\TestNotification), Array)
#14 [internal function]: Illuminate\Notifications\SendQueuedNotifications->handle(Object(Illuminate\Notifications\ChannelManager))
#15 <root>\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#16 <root>\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 <root>\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 <root>\vendor\laravel\framework\src\Illuminate\Container\Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 <root>\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#20 <root>\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Illuminate\Notifications\SendQueuedNotifications))
#21 <root>\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Notifications\SendQueuedNotifications))
#22 <root>\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 <root>\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(42): Illuminate\Bus\Dispatcher->dispatchNow(Object(Illuminate\Notifications\SendQueuedNotifications), false)
#24 <root>\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(69): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#25 <root>\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(291): Illuminate\Queue\Jobs\Job->fire()
#26 <root>\vendor\barryvdh\laravel-async-queue\src\Console\AsyncCommand.php(81): Illuminate\Queue\Worker->process('async', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#27 <root>\vendor\barryvdh\laravel-async-queue\src\Console\AsyncCommand.php(59): Barryvdh\Queue\Console\AsyncCommand->processJob('async', '84', Object(Illuminate\Queue\WorkerOptions))
#28 [internal function]: Barryvdh\Queue\Console\AsyncCommand->fire(Object(Illuminate\Queue\WorkerOptions))
#29 <root>\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#30 <root>\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#31 <root>\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#32 <root>\vendor\laravel\framework\src\Illuminate\Container\Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#33 <root>\vendor\laravel\framework\src\Illuminate\Console\Command.php(182): Illuminate\Container\Container->call(Array)
#34 <root>\vendor\symfony\console\Command\Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#35 <root>\vendor\laravel\framework\src\Illuminate\Console\Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#36 <root>\vendor\symfony\console\Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 <root>\vendor\symfony\console\Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\Queue\Console\AsyncCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 <root>\vendor\symfony\console\Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 <root>\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 <root>\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 {main}  
```

**Comment by pinodex** [comment]
Err. Looks like it was my fault. I have this line in my `ViewServiceProvider.php`
```
$twig->addGlobal('current_route', request()->route()->getName());
```

`request()->route()` returns null when rendering the view for the email.

Closing this now. Thanks.
